### ISSUE TITLE
App created using electron + angularjs2 wont invoke asprise scanner js UI or native scanner UI

### ISSUE THREAD

**Issue by sy-naveen** [Asprise/scannerjs.javascript-scanner-web-twain-wia-browsers-scanner.js#1]
App created using electron + angularjs2 wont invoke asprise scanner js UI or native scanner UI

Electron version: 1.3.3
OS : windows 10

Expected behavior : 

 It has to show this window
![acbc7f90a07e4d35a5a7570c45846e64](https://cloud.githubusercontent.com/assets/23548303/22796827/ed5083ea-ef21-11e6-9c26-ed74251d2b53.png)

Actual behavior :
This is working fine, with just angular2. If we combine it with electron the asprise scanner UI wont show.

Reproduce:
You can watch the demo [here](http://htmlpreview.github.io/?https://github.com/Asprise/scannerjs.javascript-scanner-access-in-browsers-chrome-ie.scanner.js/blob/master/demo-01-scan-display-jpg.htm) in browser its showing the asprise UI. But in electron app it wont show

**Comment by Asprise** [comment]
Thanks for reporting it. We're investigating the issue.

**Comment by ajmakoni** [comment]
Hello Asprise team, is there any update on this issue?

**Comment by Asprise** [comment]
To access scanner.js in Electron apps:

Add the following line before loading scanner.js to resolve the issue:

```
<script> window["global_scanner"] = true; </script>
<script type="text/javascript" src="https://asprise.azureedge.net/scannerjs/scanner.js"></script>            
```

Alternatively, you can put it in preload.js:

```
win = new BrowserWindow({width: 800, height: 600,     webPreferences: {
  preload: path.join(__dirname, 'preload.js')
}});
win.loadURL('http://asprise.com/scan/scannerjs/demo/scanner.js-demo.html');
``` 

with preload.js:

`window["global_scanner"] = true;`
