### ISSUE TITLE
Host on localhost

### ISSUE THREAD

**Issue by HassanDomeDenea** [Asprise/scannerjs.javascript-scanner-web-twain-wia-browsers-scanner.js#2]
Greetings
I'm developing web application hosted on localhost with php/apache to enable two users on network to scan their documents.

Messages regarding evaluation keep appearing, should I buy licences for localhost? and how about ip changes in each computer?

**Comment by Asprise** [comment]
Hi, you can test on common hosts and ips (e.g., "localhost", "127.0.0.1" and "::1"), however, we are unable to issue license for them. One exception is Electron applications.
